name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: node:latest

    steps:
      - uses: actions/checkout@v2
        name: Build the Docker image
      #登录docker
      - name: Login to DockerHub
        user: smallzip/docker-githubaction
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
